name: debut_env
dependencies:
- altair=1.0.0=py34_0
- argcomplete=0.9.0=py34_0
- babel=1.3=py34_0
- backports_abc=0.4=py34_0
- bitarray=0.8.1=py34_0
- blaze-core=0.8.2=np19py34_0
- cairo=1.12.18=6
- cffi=1.1.2=py34_0
- cloog=0.18.0=0
- colorama=0.3.3=py34_0
- conda-build=1.16.0=py34_0
- configparser=3.5.0b2=py34_0
- coverage=4.2=py34_0
- curl=7.43.0=1
- cycler=0.10.0=py34_0
- datashape=0.4.6=np19py34_0
- decorator=4.0.10=py34_0
- entrypoints=0.2.2=py34_0
- flask=0.10.1=py34_1
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- gcc=4.8.5=6
- glib=2.43.0=1
- gmp=5.1.2=2
- greenlet=0.4.7=py34_0
- h5py=2.5.0=np19py34_3
- harfbuzz=0.9.39=1
- icu=56.1=4
- idna=2.0=py34_0
- ipykernel=4.4.1=py34_0
- ipython=5.1.0=py34_0
- ipython_genutils=0.1.0=py34_0
- ipywidgets=4.1.1=py34_0
- isl=0.12.2=0
- jbig=2.1=0
- jdcal=1.0=py34_0
- jedi=0.8.1=py34_0
- jinja2=2.8=py34_1
- jpeg=8d=0
- jsonschema=2.5.1=py34_0
- jupyter=1.0.0=py34_3
- jupyter_client=4.3.0=py34_0
- jupyter_console=5.0.0=py34_0
- jupyter_core=4.1.1=py34_0
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- markupsafe=0.23=py34_2
- matplotlib=1.5.1=np111py34_0
- mistune=0.7.2=py34_0
- mkl=11.3.3=0
- mpc=1.0.1=0
- mpfr=3.1.2=0
- nbconvert=4.2.0=py34_0
- nbformat=4.1.0=py34_0
- ncurses=5.9=8
- networkx=1.10=py34_0
- notebook=4.2.2=py34_0
- numba=0.20.0=np19py34_0
- numexpr=2.6.1=np111py34_0
- numpy=1.11.1=py34_0
- odo=0.3.3=np19py34_0
- openssl=1.0.2h=1
- pandas=0.18.1=np111py34_0
- pango=1.39.0=1
- patchelf=0.6=0
- path.py=8.2.1=py34_0
- pexpect=4.0.1=py34_0
- pickleshare=0.7.3=py34_0
- pip=8.1.2=py34_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py34_0
- psutil=2.2.1=py34_0
- ptyprocess=0.5.1=py34_0
- py=1.4.31=py34_0
- pycparser=2.14=py34_0
- pycrypto=2.6.1=py34_0
- pygments=2.1.3=py34_0
- pyopenssl=0.15.1=py34_1
- pyparsing=2.1.4=py34_0
- pyqt=4.11.4=py34_4
- pytables=3.2.2=np110py34_0
- pytest=2.9.2=py34_0
- pytest-cov=2.3.1=py34_0
- python=3.4.5=0
- python-dateutil=2.5.3=py34_0
- pytz=2016.6.1=py34_0
- pyzmq=15.4.0=py34_0
- qt=4.8.7=4
- qtconsole=4.2.1=py34_0
- r=3.2.2=0
- r-kernsmooth=2.23_15=r3.2.2_0a
- r-lattice=0.20_33=r3.2.2_0a
- r-mass=7.3_45=r3.2.2_0a
- r-matrix=1.2_2=r3.2.2_0a
- r-mgcv=1.8_9=r3.2.2_0a
- r-recommended=3.2.2=r3.2.2_0
- r-rpart=4.1_10=r3.2.2_0a
- readline=6.2=2
- redis=2.6.9=0
- sas7bdat=2.0.7=py34_0
- scikit-image=0.11.3=np19py34_0
- scipy=0.18.0=np111py34_0
- seaborn=0.7.1=py34_0
- setuptools=25.1.6=py34_0
- simplegeneric=0.8.1=py34_1
- sip=4.18=py34_0
- six=1.10.0=py34_0
- sockjs-tornado=1.0.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- sqlalchemy=1.0.8=py34_0
- sqlite=3.13.0=0
- system=5.8=2
- terminado=0.6=py34_0
- tk=8.5.18=0
- tornado=4.4.1=py34_0
- traitlets=4.2.2=py34_0
- wcwidth=0.1.7=py34_0
- wheel=0.29.0=py34_0
- xlrd=1.0.0=py34_0
- xlsxwriter=0.7.3=py34_0
- xz=5.2.2=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - blaze==0.8.2
  - cryptography==0.9.1
  - ipython-genutils==0.1.0
  - joblib==0.10.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.1
  - jupyterlab==0.1.1
  - mpld3==0.2
  - ordereddict==1.1
  - prompt-toolkit==1.0.3
  - rpy2==2.8.1
  - scikit-learn==0.18.dev0
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.2
  - wmctrl==0.3

